services:
  db:
    image: postgres:16.9
    container_name: citypulse-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: citypulse
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: sh -c "npx prisma migrate deploy && npm start"
    environment:
      DATABASE_URL: "postgresql://postgres:51PJtN7Nv4uF53Lc@db:5432/citypulse?schema=public"
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pgdata:
