services:
  db:
    image: 'postgres:16.9'
    container_name: citypulse-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: citypulse
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
