export enum ErrorCodes {
    // Authentication Errors
    AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
    AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
    AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
    AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
    AUTH_EMAIL_ALREADY_IN_USE = 'AUTH_EMAIL_ALREADY_IN_USE',
    AUTH_INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  
    // Validation Errors
    VALIDATION_REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
    VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
    
    // Resource Errors
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
    
    // Server Errors
    SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',

  }
  