


export const EVENT_LIMITS = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 50,
  DESCRIPTION_MIN_LENGTH: 30,
  DESCRIPTION_MAX_LENGTH: 1000,
  LOCATION_MIN_LENGTH: 5,
  LOCATION_MAX_LENGTH: 255,
};


export const USER_LIMITS = {
  PASSWORD_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
  NAME_MIN_LENGTH: 5,
  USERNAME_MAX_LENGTH: 30,
  USERNAME_MIN_LENGTH: 3,
  BIO_MAX_LENGTH: 500,
};