


export const EVENT_LIMITS = {
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 50,
  DESCRIPTION_MIN_LENGTH: 30,
  DESCRIPTION_MAX_LENGTH: 1000,
  LOCATION_MIN_LENGTH: 5,
  LOCATION_MAX_LENGTH: 255,
};


export const USER_LIMITS = {
  PASSWORD_MIN_LENGTH: 3,
  NAME_MAX_LENGTH: 50,
  NAME_MIN_LENGTH: 5,
  USERNAME_MAX_LENGTH: 30,
  USERNAME_MIN_LENGTH: 3,
  BIO_MAX_LENGTH: 500,
};

export const RATE_LIMITS = {
  GENERAL_WINDOW_MS: 5 * 60 * 1000, // 5 minutes
  GENERAL_MAX_REQUESTS: 500,

  AUTH_WINDOW_MS: 10 * 60 * 1000, // 10 minutes
  AUTH_MAX_REQUESTS: 10,

  EVENT_CREATION_WINDOW_MS: 24 * 60 * 60 * 1000, // 24 hours
  EVENT_CREATION_MAX_REQUESTS: 5,
};